field: 639db3fc-cfd4-4523-a2e8-2ac5effb3522 # about
fieldLayouts:
  90fe6753-a117-4edb-8913-42224d16173d:
    tabs:
      -
        elements:
          -
            fieldUid: 6fb6a84c-ac77-4355-b483-06f78d791539 # body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6fb6a84c-ac77-4355-b483-06f78d791539: # body
    columnSuffix: null
    contentColumnType: mediumtext
    fieldGroup: null
    handle: body
    instructions: ''
    name: body
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: mediumtext
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: body
name: aboutcontent
sortOrder: 1
