field: e3c14bdc-b578-4588-bce9-7dc0f8553072 # inhoudzelf
fieldLayouts:
  1b01a206-5352-47d0-9da1-6a221026d0a6:
    tabs:
      -
        elements:
          -
            fieldUid: f45f3568-3d9c-4779-b17c-26458592de2f # videolink
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  f45f3568-3d9c-4779-b17c-26458592de2f: # videolink
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: videolink
    instructions: 'Zet hier een video link in.'
    name: videolink
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: videolink
name: videolink
sortOrder: 2
