columnSuffix: null
contentColumnType: string
fieldGroup: 417ad68e-f480-4c58-bc24-a31574f1c928 # blogpost
handle: headimage
instructions: ''
name: headimage
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:3b49d805-1ae4-41ab-ad93-00de8e3a56c3' # images
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:3b49d805-1ae4-41ab-ad93-00de8e3a56c3' # images
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
