columnSuffix: null
contentColumnType: string
fieldGroup: 8886d58d-cb48-4775-9092-f5615f900343 # about
handle: navbarfield
instructions: ''
name: navbarfield
searchable: false
settings:
  contentTable: '{{%matrixcontent_navbarfield}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
