defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1a7ded85-cd10-4685-8696-21042404ec46: # Blog
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
